### ISSUE TITLE
这个插件的原作者好像一直都不愿意添加中文支持啊

### ISSUE THREAD

**Issue by ZacharyJia** [lychichem/zotfile#17]
我看你之前提的PR也没有被合并进去。现在装了你的翻译版本之后，自动更新又更新到原版去了，有没有什么比较方便的办法不用每次都手动重装。

**Comment by lychichem** [comment]
@ZacharyJia 我当时提交翻译的本意是希望他merge，现在那边不merge的话，如果我不改更新链接你更新了肯定是会更新到他的无翻译版本的。你可以手动改更新链接，或者我看看要不要真的独立出来更新。主要是我不会操作travis ci保留每次构建出的xpi供你们下载，而要是直接把一个xpi放git库里会造成未来库体积的膨胀

**Comment by ZacharyJia** [comment]
我试一下吧，我感觉应该不难

**Comment by lychichem** [comment]
> 我试一下吧，我感觉应该不难

把更新链接改成无效链接的话是没一点难度，主要是我想找个人教我弄下travis……我现在用的travis脚本是抄原项目的，感觉最后的上传设置有问题，也没弄保留设置

**Comment by ZacharyJia** [comment]
@lychichem 我试了一下，问题不大。项目目前的配置可以直接使用。 

在`.travis.yml`这个文件里，配置了在make执行完成之后，把打包生成xpi文件上传到https://anonfile.com这个网站上（也就是最后一句的curl），相当于一个临时文件存储。这条命令执行的结果当中，会把这个文件的url返回回来。

这样的话，只要激活这个项目的travis配置之后，travis应该会在你每次push到master分支上之后自动执行build。你只需要在每次想要发行新版本的时候，去travis上面，找到对应的job的执行日志，按照curl命令的返回值当中的url下载生成的文件即可。这样你就可以在github上发布release的时候添加那个文件作为附件了。

既然对方不愿意合并中午的翻译，我比较建议独立发布。当然可能会麻烦你了，如果需要我可以帮忙。

**Comment by lychichem** [comment]
> @lychichem 我试了一下，问题不大。项目目前的配置可以直接使用。
> 
> 在`.travis.yml`这个文件里，配置了在make执行完成之后，把打包生成xpi文件上传到https://anonfile.com 这个网站上（也就是最后一句的curl），相当于一个临时文件存储。这条命令执行的结果当中，会把这个文件的url返回回来。
> 
> 这样的话，只要激活这个项目的travis配置之后，travis应该会在你每次push到master分支上之后自动执行build。你只需要在每次想要发行新版本的时候，去travis上面，找到对应的job的执行日志，按照curl命令的返回值当中的url下载生成的文件即可。这样你就可以在github上发布release的时候添加那个文件作为附件了。
> 
> 既然对方不愿意合并中午的翻译，我比较建议独立发布。当然可能会麻烦你了，如果需要我可以帮忙。

其实我刚刚GitHub token已经准备好了，不会写勾到release的travis脚本orz而且好像因为抄了他的脚本导致我这边配置app方式安装的travis的时候出了问题不识别……

**Comment by ZacharyJia** [comment]
@lychichem 你是说它的发布到GitHub的release也是自动的吗？

**Comment by lychichem** [comment]
> @lychichem 你是说它的发布到GitHub的release也是自动的吗？

不是，是travis本来就可以跳过中转网盘直接传到github release的（只是我不会搞），所以想找个会的教一下……

**Comment by ZacharyJia** [comment]
> > @lychichem 你是说它的发布到GitHub的release也是自动的吗？
> 
> 不是，是travis本来就可以跳过中转网盘直接传到github release的（只是我不会搞），所以想找个会的教一下……

我看他原来仓库里的travis没用到这个呀，只配置了上传到中间网盘

**Comment by lychichem** [comment]
> > > @lychichem 你是说它的发布到GitHub的release也是自动的吗？
> > 
> > 
> > 不是，是travis本来就可以跳过中转网盘直接传到github release的（只是我不会搞），所以想找个会的教一下……
> 
> 我看他原来仓库里的travis没用到这个呀，只配置了上传到中间网盘

所以我要动手啊……然后卡在不会弄了……

**Comment by ZacharyJia** [comment]
> > > > @lychichem 你是说它的发布到GitHub的release也是自动的吗？
> > > 
> > > 
> > > 不是，是travis本来就可以跳过中转网盘直接传到github release的（只是我不会搞），所以想找个会的教一下……
> > 
> > 
> > 我看他原来仓库里的travis没用到这个呀，只配置了上传到中间网盘
> 
> 所以我要动手啊……然后卡在不会弄了……

  #18 我在这里搞定了，你可以试一下

**Comment by lychichem** [comment]
@ZacharyJia 测试了下可以，感谢大佬出手

**Comment by specter119** [comment]
2021年了，真是辛苦了。
